name: Scrape Data

on:
  schedule:
    - cron: "0 1 * * *" # 6:30am IST
  workflow_dispatch:

jobs:
  run-scraper:
    uses: coronasafe/leaderboard/.github/workflows/scraper.yaml@reusable-scraper-workflow
    if: github.ref == 'refs/heads/main'
    permissions:
      issues: read
      pull-requests: read
      contents: write
    secrets: inherit
    with:
      slack-eod-channel: ${{ vars.SLACK_EOD_CHANNEL }}
